# Copyright (c) 2025, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This Dockerfile installs the necessary dependencies for streaming speech translation with vLLM.

ARG BASE_IMAGE=pytorch/pytorch:2.9.0-cuda12.8-cudnn9-runtime

FROM ${BASE_IMAGE}

ARG GIT_URL="https://github.com/NVIDIA-NeMo/Speech.git"
ARG CHECKOUT="main"

ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y \
  libtool libltdl-dev \
  libsndfile1 sox \
  libfreetype6 \
  libsox-fmt-all \
  swig \
  ffmpeg \
  libavdevice-dev \
  git \
  build-essential \
  cmake && \
  rm -rf /var/lib/apt/lists/*

# Install NeMo
RUN git clone --recursive ${GIT_URL} nemo_dir && cd nemo_dir && \
  git checkout $CHECKOUT && \
  pip install ".[all]"

# Install vLLM for streaming speech translation
RUN pip install vllm==0.12.0